name: Deploy Admin

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: mahek-admin
  PROJECT_ID: mahek-deploy
  REGION: asia-south1
  REGISTRY_REGION: asia-south1
  REPOSITORY: mahek-repo

  VITE_CLOUDINARY_BASE_URL: ${{ secrets.VITE_CLOUDINARY_BASE_URL }}
  VITE_CLOUDINARY_CLOUD_NAME: ${{ secrets.VITE_CLOUDINARY_CLOUD_NAME }}
  VITE_CLOUDINARY_UPLOAD_PRESET: ${{ secrets.VITE_CLOUDINARY_UPLOAD_PRESET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Select environment variables
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "SERVICE=admin-prod" >> $GITHUB_ENV
            echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL_PROD }}" >> $GITHUB_ENV
          else
            echo "SERVICE=admin-staging" >> $GITHUB_ENV
            echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL_STAGING }}" >> $GITHUB_ENV
          fi


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}


      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2


      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker $REGISTRY_REGION-docker.pkg.dev --quiet


      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_API_BASE_URL="$VITE_API_BASE_URL" \
            -t $REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} .


      - name: Push Docker image
        run: |
          docker push \
          $REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }}


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE \
            --image=$REGISTRY_REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:${{ github.sha }} \
            --region=$REGION \
            --platform=managed \
            --allow-unauthenticated